"""Initial_tables

Revision ID: 65781aedaf17
Revises: 
Create Date: 2026-02-16 14:36:36.134156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65781aedaf17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
